-- Version 0 upgrade script

-- Contains information about currently installed versions
CREATE TABLE IF NOT EXISTS DBUPGRADE (
    Version INT PRIMARY KEY,
    DateInstalled TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS BOARDS (
    ROUTE VARCHAR(4) PRIMARY KEY,
    TITLE TEXT NOT NULL,
    DESCRIPTION TEXT NOT NULL
);

-- FIXME

INSERT INTO BOARDS (ROUTE, TITLE, DESCRIPTION) VALUES ('i', 'Idol', 'Board for discussion of idols');

CREATE TABLE IF NOT EXISTS POSTS (
    Id BIGSERIAL PRIMARY KEY,
    BOARD VARCHAR(4),
    TITLE VARCHAR(128),
    AUTHOR VARCHAR(128) DEFAULT 'Anonymous',
    POSTED BIGINT NOT NULL,
    CONTENT VARCHAR(256) NOT NULL,
    HASH VARCHAR(32) NOT NULL,
    PARENT BIGINT
);