-- Version 0 upgrade script

-- Contains information about currently installed versions
CREATE TABLE IF NOT EXISTS DBUPGRADE (
    VERSION INT PRIMARY KEY,
    DATEINSTALLED TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS BOARDS (
    ROUTE VARCHAR(4) PRIMARY KEY,
    TITLE TEXT NOT NULL,
    DESCRIPTION TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS POSTS (
    ID BIGSERIAL PRIMARY KEY,
    BOARD VARCHAR(4) NOT NULL,
    TITLE VARCHAR(128),
    AUTHOR VARCHAR(128) DEFAULT 'Anonymous',
    POSTED BIGINT NOT NULL,
    CONTENT VARCHAR(256) NOT NULL,
    AUTHORHASH CHAR(36) NOT NULL,
    PARENTPOSTID BIGINT,
    PICTUREFILENAME VARCHAR(128),
    FILEDATA BYTEA,
    HIDDEN BOOLEAN DEFAULT FALSE,
    STICKIED BOOLEAN DEFAULT FALSE,
    CONSTRAINT FK_POST_PARENT FOREIGN KEY (PARENTPOSTID) REFERENCES POSTS (ID) ON DELETE CASCADE,
    CONSTRAINT FK_POST_BOARD FOREIGN KEY (BOARD) REFERENCES BOARDS (ROUTE) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS CODES ( CODE TEXT PRIMARY KEY );

-- Default code when creating a new site. Change it when setting it up
INSERT INTO CODES VALUES ('ROOT');