-- Version 1 upgrade script

ALTER TABLE POSTS ADD COLUMN FILENAME VARCHAR(128);
ALTER TABLE POSTS ADD COLUMN FILEDATA BYTEA;

ALTER TABLE POSTS ADD CONSTRAINT FK_POST_PARENT FOREIGN KEY (PARENT) REFERENCES POSTS (ID) ON DELETE CASCADE;
ALTER TABLE POSTS ADD CONSTRAINT FK_POST_BOARD FOREIGN KEY (BOARD) REFERENCES BOARDS (ROUTE) ON DELETE CASCADE;

CREATE TABLE IF NOT EXISTS ADMINS (
    ID SERIAL PRIMARY KEY,
    USERNAME VARCHAR(128) UNIQUE NOT NULL,
    PASSWORDHASH CHAR(64) NOT NULL,
    PASSWORDSALT CHAR(36) NOT NULL,
    DATEREGISTERED BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS INVITES (
    INVITE CHAR(36) PRIMARY KEY
);

-- DEFAULT INVITE FOR ROOT ADMIN. DELETED WHEN USED
INSERT INTO INVITES VALUES ('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX');

CREATE TABLE IF NOT EXISTS SESSIONS (
    TOKEN CHAR(36) PRIMARY KEY,
    ADMIN INT NOT NULL
);